# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(621, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_12.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.imagen = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.imagen.setFont(font)
        self.imagen.setText("")
        self.imagen.setPixmap(QtGui.QPixmap("./Logo.png"))
        self.imagen.setObjectName("imagen")
        self.horizontalLayout_12.addWidget(self.imagen)
        self.verticalLayout_15.addLayout(self.horizontalLayout_12)
        self.verticalLayout_3.addLayout(self.verticalLayout_15)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pathFile = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pathFile.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathFile.sizePolicy().hasHeightForWidth())
        self.pathFile.setSizePolicy(sizePolicy)
        self.pathFile.setMaximumSize(QtCore.QSize(100678, 25))
        self.pathFile.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pathFile.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.pathFile.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.pathFile.setObjectName("pathFile")
        self.horizontalLayout_9.addWidget(self.pathFile)
        self.cargarArchivo = QtWidgets.QPushButton(self.centralwidget)
        self.cargarArchivo.setObjectName("cargarArchivo")
        self.horizontalLayout_9.addWidget(self.cargarArchivo)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.cbseleccionarAlgoritmo = QtWidgets.QComboBox(self.centralwidget)
        self.cbseleccionarAlgoritmo.setObjectName("cbseleccionarAlgoritmo")
        self.horizontalLayout_4.addWidget(self.cbseleccionarAlgoritmo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.cbVisualizacion = QtWidgets.QComboBox(self.centralwidget)
        self.cbVisualizacion.setMaxVisibleItems(8)
        self.cbVisualizacion.setObjectName("cbVisualizacion")
        self.horizontalLayout_3.addWidget(self.cbVisualizacion)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.cbGenes = QtWidgets.QComboBox(self.centralwidget)
        self.cbGenes.setObjectName("cbGenes")
        self.horizontalLayout_3.addWidget(self.cbGenes)
        self.procesar = QtWidgets.QPushButton(self.centralwidget)
        self.procesar.setObjectName("procesar")
        self.horizontalLayout_3.addWidget(self.procesar)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.grafica = QtWidgets.QGridLayout()
        self.grafica.setObjectName("grafica")
        self.verticalLayout_4.addLayout(self.grafica)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_4.addWidget(self.progressBar)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_13.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_13.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_13.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_13.addWidget(self.label_8)
        self.horizontalLayout_11.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem4)
        self.vectoBinarizado = QtWidgets.QLabel(self.centralwidget)
        self.vectoBinarizado.setText("")
        self.vectoBinarizado.setObjectName("vectoBinarizado")
        self.verticalLayout_14.addWidget(self.vectoBinarizado)
        self.thValue = QtWidgets.QLabel(self.centralwidget)
        self.thValue.setText("")
        self.thValue.setObjectName("thValue")
        self.verticalLayout_14.addWidget(self.thValue)
        self.pValue = QtWidgets.QLabel(self.centralwidget)
        self.pValue.setText("")
        self.pValue.setObjectName("pValue")
        self.verticalLayout_14.addWidget(self.pValue)
        self.horizontalLayout_11.addLayout(self.verticalLayout_14)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem5)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_11.addWidget(self.label_5)
        self.horizontalLayout_11.addLayout(self.verticalLayout_11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 621, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Multiscale Binarization of Gene Expression\n"
"Data for Reconstructing Boolean Networks"))
        self.pathFile.setPlainText(_translate("MainWindow", "Load file ..."))
        self.cargarArchivo.setText(_translate("MainWindow", "Load file"))
        self.label_2.setText(_translate("MainWindow", "Algorithm:     "))
        self.label.setText(_translate("MainWindow", "Visualization:"))
        self.label_9.setText(_translate("MainWindow", "Gene:"))
        self.procesar.setText(_translate("MainWindow", "Run "))
        self.label_4.setText(_translate("MainWindow", "Answer"))
        self.label_6.setText(_translate("MainWindow", "Binarized vector:"))
        self.label_7.setText(_translate("MainWindow", "Threshold:"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p>Proyecto de Grado1 PGR1<br/>Tatiana Higuera<br/>Giovanny Sissa</p></body></html>"))

